### ISSUE TITLE
List products kits 

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/modules-api#16]

**Comment by leomp12** [comment]
👀 na verdade por aqui você não vai renderizar nada...
O módulo já poderia estar sendo consumido pela página de produtos, só que não tem porque fazer isso atualmente porque não há retorno previsto que seja útil pra página de produtos.
O TODO aqui é editar o https://github.com/ecomplus/modules-api/blob/master/routes/apply_discount.js#L230-L327 pra adicionar uma propriedade (provavelmente um array de objetos) que represente descontos por compre junto, baseado no produto enviado nos parâmetros (https://github.com/ecomplus/modules-api/blob/master/routes/apply_discount.js#L17-L84).

**Comment by leomp12** [comment]
Talvez igual o que já tem no schema de produtos mesmo:

```js
    'buy_together': {
      'type': 'array',
      'maxItems': 20,
      'items': {
        'type': 'object',
        'required': [ 'this' ],
        'additionalProperties': false,
        'maxProperties': 50,
        'patternProperties': {
          '^([a-f0-9]{24}|this)$': {
            'type': 'object',
            'required': [ 'quantity' ],
            'additionalProperties': false,
            'properties': {
              'quantity': {
                'type': 'number',
                // 'multipleOf': 0.0001,
                'minimum': 0,
                'maximum': 9999999,
                'description': 'Product quantity'
              },
              'discount': {
                'type': 'object',
                'required': [ 'value' ],
                'additionalProperties': false,
                'properties': {
                  'type': {
                    'type': 'string',
                    'enum': [ 'percentage', 'fixed' ],
                    'default': 'percentage',
                    'description': 'Discount type'
                  },
                  'value': {
                    'type': 'number',
                    // 'multipleOf': 0.0001,
                    'minimum': -99999999,
                    'maximum': 99999999,
                    'description': 'Discount value, percentage or fixed'
                  }
                },
                'description': 'Discount object'
              }
            },
            'description': 'Product in buy together'
          }
        },
        'description': 'This product and others composing buy together, product ID as property name'
      },
      'description': 'Buy together options'
    },
```

Mas sem o `this` no meio aí porque pode ter vários produtos nessa request e porque o `this` seria ambíguo (nessa API não existe o contexto "página de produto").

**Comment by matheusgnreis** [comment]
Fiz parecido até, no caso, quantity não tem como definir na regra do compre junto do app, por isso não coloquei

**Comment by matheusgnreis** [comment]
Vou alterar pra colocar discounts, havia deixado apenas lista de itens, tipo do desconto e valor, considerando que na página do produto teria apenas um compre junto. No caso, vou colocar esse pra ter mais de um

**Comment by matheusgnreis** [comment]
Nesse schema não tem ids dos produtos, então acho que não vou usar ele

**Comment by matheusgnreis** [comment]
https://github.com/ecomplus/modules-api/pull/17

**Comment by leomp12** [comment]
> Fiz parecido até, no caso, quantity não tem como definir na regra do compre junto do app, por isso não coloquei

A API pode/deve "ter mais que o app", o contrário é que não tem como...

> Nesse schema não tem ids dos produtos, então acho que não vou usar ele

Tem, as proriedades do objeto são IDs de produtos: `patternProperties['^([a-f0-9]{24}|this)$']`. Dessa forma os IDs não podem repetir, se você definir o schema com um array de objetos com a proriedade `_id` vai ser possível retornar 2 objetos com o mesmo ID (repetir o produto duas vezes no compre junto).

**Comment by leomp12** [comment]
`[a-f0-9]{24}` é o RegEx do object ID (IDs de produtos, categorias, marcas, pedidos etc)

**Comment by leomp12** [comment]
Tá até na descrição no schema inclusive: _This product and others composing buy together, **product ID as property name**_

**Comment by matheusgnreis** [comment]
No caso entao, tem a propriedade product id. Eu vi o regex, só não sabia que dava pra colocar assim referenciando a propriedade

**Comment by leomp12** [comment]
Não é que "tem a propriedade product id", o product ID nesse caso é a propriedade, nesse schema fica algo como:

```json
{
  "1234567": {
    "quantity": 1,
    "discount": { ... }
  }
}
```

Nesse caso `123456` seria o ID do produto.
O `quantity` poderia ser opcional aqui também.

**Comment by leomp12** [comment]
Mas isso aí só funcionaria pra compre junto com 2 produtos por vez https://github.com/ecomplus/modules-api/pull/17#discussion_r925036339
Vai ser isso mesmo?
